# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Launch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Launch

  target 'LaunchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LaunchUITests' do
    # Pods for testing
  end

  # Pods for Launch
  pod 'Alamofire'
  pod 'SnapKit'


end
